<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LoginSucccess</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>4a531b31-77e6-498b-aa97-1751e67d168b</testSuiteGuid>
   <testCaseLink>
      <guid>06d3b7c7-7d34-41c1-8c75-82925208fe26</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/G1_Login/S01_TC1_SuccessfullyLogin</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>befd7978-e302-4a9d-b1b0-ca038621f087</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/usernameSource</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>befd7978-e302-4a9d-b1b0-ca038621f087</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>2f7c3c3a-d282-428e-84d6-55af060f3609</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3b70c95-70b8-4610-a2e2-75476487bc4e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
